=== Valknut/ASPStrings/Project/Tank_Platoons/Tank_Platoons/App_Data/TPlatoon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tank_platoon (name,nation,rating,tropheys,crew,win_rate)>
    <!ATTLIST tank_platoon att_id_tp ID #REQUIRED >
    <!ELEMENT win_rate (#PCDATA) >
    <!ELEMENT nation (#PCDATA) >
    <!ELEMENT rating (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT tropheys (trophey+)>
        <!ELEMENT trophey (year,place,league)>
            <!ATTLIST trophey att_id_trophey  ID #REQUIRED > 
            <!ELEMENT year (#PCDATA)>
            <!ELEMENT place (#PCDATA)>
            <!ELEMENT league (league_name,league_country) >
                <!ATTLIST league att_id_league ID #REQUIRED >
                <!ELEMENT league_name (#PCDATA)>
                    <!ATTLIST league_name l_type ( Професионална | Аматьорска ) #REQUIRED  >
                <!ELEMENT league_country (#PCDATA) >    
    <!ELEMENT crew (member+)>
        <!ELEMENT member (first_name,last_name,nickname,age,date_of_birth,country,tank,personal_win_rate)>
            <!ATTLIST member att_id_member  ID #REQUIRED >
            <!ATTLIST member att_platoon_pos  CDATA #REQUIRED >
            <!ATTLIST member strategic_position  (Светляк|Защитник|Нашественик|Снайперист|Артилерист) #REQUIRED >
            <!ATTLIST member gender (мъжки | женски) #REQUIRED >
            <!ELEMENT last_name (#PCDATA)>
            <!ELEMENT first_name (#PCDATA)>
            <!ELEMENT age (#PCDATA)>
            <!ELEMENT date_of_birth (day,month,birth_year) >
                <!ELEMENT birth_year (#PCDATA) >
                <!ELEMENT day (#PCDATA) >
                <!ELEMENT month (#PCDATA) >
            <!ELEMENT country (#PCDATA)>
            <!ELEMENT personal_win_rate (#PCDATA) >
                <!ATTLIST personal_win_rate colour (Зелен | Жълт | Червен) #REQUIRED >
            <!ELEMENT nickname (#PCDATA)>
            <!ELEMENT tank (tier,tank_name,tank_nation,image,gun_penetration,top_speed)>
                <!ATTLIST tank att_id_tank ID #REQUIRED >
                <!ATTLIST tank type  (Тежък_танк|Среден_танк|Лек_танк|ПТ-САУ|САУ) #REQUIRED >  
                <!ATTLIST tank ammo_type (ББ | БП | ОФ | КС | БОФ) #REQUIRED >
                <!ELEMENT gun_penetration (#PCDATA) >
                <!ELEMENT top_speed (#PCDATA) >
                <!ELEMENT image (#PCDATA) >
                <!ELEMENT tier (#PCDATA)>
                <!ELEMENT tank_name (#PCDATA)>
                <!ELEMENT tank_nation (#PCDATA)>

=== Valknut/ASPStrings/Project/Tank_Platoons/Tank_Platoons/App_Data/tp3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tank_platoon SYSTEM "TPlatoon.dtd">
<tank_platoon att_id_tp="tp3">
  <name>xVm</name>
  <nation>Германия</nation>
  <rating>5</rating>
  <personal_win_rate />50,21<tropheys><trophey att_id_trophey="t1" att_id_league="l2"><year>1999</year><place>3</place><league><league_name l_type="Професионална">WWOTF</league_name><league_country>Германия</league_country></league></trophey></tropheys><crew><member att_id_member="m1" gender="мъжки" att_platoon_pos="Капитан" strategic_position="Защитник"><first_name>Франц</first_name><last_name>Шуберт</last_name><age>21</age><date_of_birth><birth_year>1994</birth_year><day>19</day><month>12</month></date_of_birth><country>Германия</country><personal_win_rate colour="Зелен">53,21</personal_win_rate><nickname>shubacher</nickname><tank att_id_tank="ta1" type="Среден_танк" ammo_type="ББ"><tier>9</tier><tank_name>T-55A</tank_name><tank_nation>Немски</tank_nation><image>t55a.jpg</image><gun_penetration>201</gun_penetration><top_speed>50</top_speed></tank></member></crew></tank_platoon>

=== Valknut/ASPStrings/Project/Tank_Platoons/Tank_Platoons/App_Data/asd.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tank_platoon SYSTEM "TPlatoon.dtd">
<tank_platoon att_id_tp="asd">
  <name>moly</name>
  <nation>asdf</nation>
  <rating>asdf</rating>
  <personal_win_rate />asdf<tropheys><trophey att_id_trophey="afd" att_id_league="fds"><year>asdf</year><place>asdf</place><league><league_name l_type="asdf">asdf</league_name><league_country>asdf</league_country></league></trophey></tropheys><crew /></tank_platoon>

=== Valknut/ASPStrings/Project/Tank_Platoons/Tank_Platoons/App_Data/thy.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tank_platoon SYSTEM "TPlatoon.dtd">
<tank_platoon att_id_tp="thy">
  <name>xVm</name>
  <nation>Германия</nation>
  <rating>5</rating>
  <personal_win_rate />50,21<tropheys><trophey att_id_trophey="t1" att_id_league="l2"><year>1999</year><place>3</place><league><league_name l_type="Професионална">WWOTF</league_name><league_country>Германия</league_country></league></trophey></tropheys><crew /></tank_platoon>

=== Valknut/ASPStrings/Project/Tank_Platoons/Tank_Platoons/App_Data/tp24.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tank_platoon SYSTEM "TPlatoon.dtd">
<tank_platoon att_id_tp="tp24">
  <name>xVma</name>
  <nation>Германияa</nation>
  <rating>5</rating>
  <personal_win_rate />50,21<tropheys><trophey att_id_trophey="g324" att_id_league="f34"><year>1999</year><place>3</place><league><league_name l_type="Професионална">WWOTF</league_name><league_country>Германия</league_country></league></trophey></tropheys><crew /></tank_platoon>
